version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8080:80
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - 80:80